# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageGallery
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MBProgressHUD'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod "KRLCollectionViewGridLayout", "~> 1.0.0"

  target 'ImageGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageGalleryUITests' do
    # Pods for testing
  end

end
